// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDuoCards.Models;

#nullable disable

namespace MyDuoCards.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MyDuoCards.Models.DBModels.EuWord", b =>
                {
                    b.Property<int>("EnWordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnWriting")
                        .HasColumnType("TEXT");

                    b.HasKey("EnWordId");

                    b.ToTable("EuWord");
                });

            modelBuilder.Entity("MyDuoCards.Models.DBModels.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MyDuoCards.Models.DBModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPassword")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyDuoCards.Models.DBModels.UserDictionary", b =>
                {
                    b.Property<int>("UserDictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EnWordId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EuWordEnWordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserDictionaryId");

                    b.HasIndex("EuWordEnWordId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDictionaries");
                });

            modelBuilder.Entity("MyDuoCards.Models.DBModels.User", b =>
                {
                    b.HasOne("MyDuoCards.Models.DBModels.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MyDuoCards.Models.DBModels.UserDictionary", b =>
                {
                    b.HasOne("MyDuoCards.Models.DBModels.EuWord", "EuWord")
                        .WithMany("UserDictionaries")
                        .HasForeignKey("EuWordEnWordId");

                    b.HasOne("MyDuoCards.Models.DBModels.User", "User")
                        .WithOne("UserDictionary")
                        .HasForeignKey("MyDuoCards.Models.DBModels.UserDictionary", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EuWord");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyDuoCards.Models.DBModels.EuWord", b =>
                {
                    b.Navigation("UserDictionaries");
                });

            modelBuilder.Entity("MyDuoCards.Models.DBModels.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("MyDuoCards.Models.DBModels.User", b =>
                {
                    b.Navigation("UserDictionary");
                });
#pragma warning restore 612, 618
        }
    }
}
